# Generated by Django 4.1.5 on 2023-01-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='another_field',
            field=models.CharField(choices=[('profile', 'tester'), ('profile2', 'developer')], default='DEFAULT', max_length=250),
        ),
    ]
